version: '3.1'

services:

  php-fpm:
    build: docker
    container_name: 'php_apricode'
    ports:
      - 9000:9000
    volumes:
      - ./:/app
    working_dir: /app

  nginx:
    image: nginx
    container_name: 'nginx_apricode'
    working_dir: /app
    ports:
      - 7777:80
    volumes:
      - ./:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

  mysql:
      image: mysql:8.0
      container_name: 'mysql8_apricode'
      restart: unless-stopped
      env_file: .env
      command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci --init-file /data/application/init.sql
      volumes:
        - ./docker/init.sql:/data/application/init.sql
      ports:
          - 3306:3306
      environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=apricode

  swagger-ui:
      image: swaggerapi/swagger-ui
      container_name: swagger_ui_apricode
      ports:
        - "80:8080"
      volumes:
        - ./doc:/usr/share/nginx/html/doc
      environment:
        API_URL: doc/openapi.yaml


